// carrossel
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:20,
    nav:false,
    autoplay:true,
    autoplayout:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        964:{
            items:3
        },
        1200:{
            items:4
        }
    }
});