// carrossel
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:50,
    nav:false,
    autoplay:true,
    autoplayout:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        964:{
            items:4
        },
        1200:{
            items:5
        },
        1260:{
            items:6
        }
    }
});